### PR TITLE
revise workspace saving

### PR DESCRIPTION
**Pull request by Konfekt**
This attempts to fix the broken logic of saving a workspace before and after Vim 8.1.149

### CODE REVIEW

**Comment by jmolero** [comment]
This fixes #265 for me too. Could it be merged please? Thanks.

**Comment by Konfekt** [comment]
Awesome, good to know. Nudging @cometsong for an eventual merge.

**Comment by jmolero** [comment]
@Konfekt  However, merging this with master seems to make the problem described at #227 appear again.

**Comment by Konfekt** [comment]
There is the line

```vim
" autoload/ctrlspace/workspaces.vim (line 347)
set ssop=winsize,tabpages,buffers,sesdir
```

that disables saving the folds in `&sessionoptions`.

You could test adding these by adding the line `set ssop+=folds` or use [vim-stay](https://github.com/zhimsel/vim-stay).

**Comment by Konfekt** [comment]
Please reopen #227 to sort this out over there.

**Comment by Konfekt** [comment]
One could think about making the session options used by `vim-ctrlspace` configurable, but maybe using `vim-stay` is the cleaner solution.

**Comment by Konfekt** [comment]
How about

```vim
set ssop+=winsize,tabpages,buffers,sesdir
```

That is, `+=` instead of `=`. 

Could you test it and tell me how it works out for you?

**Comment by jmolero** [comment]
I think I don't understand much how this works, but I'm already using vim-stay to try to save the folds. It was failing before and then it started working again after an update. Seems that these changes make vim-stay unable to save the folds again. I tried the `ssop` but didn't work.

**Comment by Konfekt** [comment]
Then try adding `set ssop+=folds` as mentioned above to force `vim-ctrlspace` to save folds (I supposed that your `&ssop` included `folds`).

**Comment by Konfekt** [comment]
By the way, I am using vim-stay with vim-ctrlspace and folds are restored fine. Perhaps you could provide a minimal `vimrc` to sort this out?

**Comment by Konfekt** [comment]
Please let us pinpoint the exact error in #227.

**Comment by jyscao** [comment]
This PR looks to be a subset from the one in #277, whose commits are now merged.

@jmolero if #227 persists/reappears, please open a new issue.

**Pull request closed without merging**
