### PR TITLE
count buffers in tab if Vim started with multiple files as arguments

### PR DESCRIPTION
**Pull request by Konfekt**

### CODE REVIEW

**Comment by cometsong** [comment]
Nice one. 
Only difference is in use of spaces vs 'szw's \tabs.  I'm going to merge it anyway, then propose we just change all the tabs to spaces in the future.  
As long as we're consistent with each other, then all is well. 😄

**Comment by Konfekt** [comment]
Somehow I am having problems pushing from cloned repositories, that's why I had to copy-paste into the github editor which displayed tabs as eight spaces. I agree on converting tabs to spaces.

**Comment by cometsong** [comment]
FYI, I've done a plugin-wide conversion of **s/tabs/4-spaces/** in commit https://github.com/vim-ctrlspace/vim-ctrlspace/commit/854639bd0fc992d34e8c6b7fe6a46928b37fe9d4

Looked back through *szw*'s commit history and he changed the format of indentation several times, different number of spaces, then to tabs.  Heheh.

**Comment by Konfekt** [comment]
Okay, thanks for the heads up! Perhaps that why vim-plug complained and a `git pull --force` was in order.

**Comment by tail** [comment]
This seems to be causing an issue with some other plugins I'm using.  I don't see any specific error messages, but so far what I've noticed is that only the last buffer that I open actually has syntax highlighting and `vim-fugitive` doesn't appear to be loading.  I'm using `vim-plug` to manage my plugins and using neovim.  Not sure what other information might be helpful to help reproduce the issue.

**Comment by Konfekt** [comment]
@tail thank you for pointing this out. The pull request https://github.com/vim-ctrlspace/vim-ctrlspace/pull/224 should mitigate this issue

**Pull request merged**
