### PR TITLE
add punctuation characters to search

### PR DESCRIPTION
**Pull request by Konfekt**
addresses https://github.com/vim-ctrlspace/vim-ctrlspace/issues/263

### CODE REVIEW

**Comment by jyscao** [comment]
One thing I think you should consider is how adding the `punctuation` list might affect the `s:findLowestSearchNoise` and `s:findSubsequence` functions in `engine.vim`.

It could be the case that the current ranking algorithm handles the punctuation additions perfectly well, but I at least can't confirm that without testing it out some.

**Comment by Konfekt** [comment]
Thank you for pointing out this possible point of failure! The punctuation characters are now escaped.

**Comment by jyscao** [comment]
As already mentioned in #263, I do think this is a good idea generally speaking. I checked out your branch implementing this feature, and my brief testing of it looks good.

However as this does introduce a non insignificant change in behavior, I'd like to err on the side of caution and do some more thorough testing before merging this in as the default and only behavior. 

If users really want this capability to be added to the plugin asap, I think a reasonable thing to do would be to provide an option (something along the lines of `g:CtrlSpaceExtraSearchChars` for example), which they can then set to either a list or a string (whatever is more appropriate from an implementation standpoint) containing all the extra characters they'd like added. And we'd explain clearly in the docs how it's used and why it exists, i.e. because for legacy reasons, punctuation chars aren't supported in search mode by default.

The main benefit of this course of action is that it helps to shift the burden of maintenance for this particular feature towards the users rather than the maintainers, which IMO makes more sense in this particular situation since this doesn't look to be a highly requested feature.

@cometsong what do you think?

**Comment by danbst** [comment]
at least dot (`.`), underscore (`_`) and slash (`/`) should be allowed by default in all cases, as those are sensible parts of file path. I don't understand reasons to exclude those from search keys. 

I'd also want space (` `) to be allowed in search, but it is less critical.

**Comment by Konfekt** [comment]
@danbst, could you test this branch? @cometsog and @jyscao : no rush, but perhaps some forecast when a decision will be taken?

**Comment by danbst** [comment]
@Konfekt I've tested, it works except for `/`. I expected `less` like behavior, where you *can* search for slash.

**Comment by Konfekt** [comment]
@danbst give the latest commit a try. Hopefully it is as simple as that.

**Comment by jyscao** [comment]
@Konfekt given that it seems more users would rather have this than not, I'd say go ahead and merge it in. If we do get people complaining that this is an unwelcomed surprise when they update, then you can consider putting it behind a feature flag. But as of now, if the feature is working as expected, then it's good enough to merge for me.

**Pull request merged**
